#!/usr/bin bash

gnuplot VolatileFlameStandOffDistance_EffectOfOxygenContent.gnu
gnuplot VolatileFlameStandOffDistance_EffectOfSize_AirOxy.gnu
gnuplot VolatileFlameStandOffDistance_EffectOfSize.gnu
gnuplot VolatileFlameStandOffDistance_EffectOfSize_SameGrid.gnu
cd figures
ps2pdf -dEPSCrop VolatileFlameStandOffDistance_EffectOfOxygenContent.eps
ps2pdf -dEPSCrop VolatileFlameStandOffDistance_EffectOfSize_AirOxy.eps
ps2pdf -dEPSCrop VolatileFlameStandOffDistance_EffectOfSize.eps
ps2pdf -dEPSCrop VolatileFlameStandOffDistance_EffectOfSize_SameGrid.eps
