#!/usr/bin bash

FlameMan -i FlameMaster_phi0_60.input
FlameMan -i FlameMaster_phi0_65.input
FlameMan -i FlameMaster_phi0_70.input
FlameMan -i FlameMaster_phi0_75.input
FlameMan -i FlameMaster_phi0_80.input
FlameMan -i FlameMaster_phi0_85.input
FlameMan -i FlameMaster_phi0_90.input
FlameMan -i FlameMaster_phi0_95.input
FlameMan -i FlameMaster_phi1_00.input
FlameMan -i FlameMaster_phi1_05.input
FlameMan -i FlameMaster_phi1_10.input
FlameMan -i FlameMaster_phi1_15.input
FlameMan -i FlameMaster_phi1_20.input
FlameMan -i FlameMaster_phi1_25.input
FlameMan -i FlameMaster_phi1_30.input
FlameMan -i FlameMaster_phi1_35.input
FlameMan -i FlameMaster_phi1_40.input
FlameMan -i FlameMaster_phi1_45.input
FlameMan -i FlameMaster_phi1_50.input
FlameMan -i FlameMaster_phi1_55.input
FlameMan -i FlameMaster_phi1_60.input
FlameMan -i FlameMaster_phi1_65.input
FlameMan -i FlameMaster_phi1_70.input
FlameMan -i FlameMaster_phi1_75.input
FlameMan -i FlameMaster_phi1_80.input
FlameMan -i FlameMaster_phi1_85.input
FlameMan -i FlameMaster_phi1_90.input
FlameMan -i FlameMaster_phi1_95.input
FlameMan -i FlameMaster_phi2_00.input
